#!/bin/bash
# build the executables for a Victron Cerbos GX
# the Victronenergy Venus SDK needs to be installed
# in my case in /opt/venus/gerbosgx
#
GXHOSTNAME=vgx.armin.d
GXUSER=root

function c_pt() {
	scp pylontech pylon2influx victrongx/lslocks victrongx/functions.sh victrongx/serstart victrongx/lock victrongx/lsusbser victrongx/start victrongx/start_pylon2influx $GXUSER@$GXHOSTNAME:/data/home/root
	scp victrongx/rc.local $GXUSER@$GXHOSTNAME:/data
}


make clean
. /opt/venus/cerbosgx/environment-setup-cortexa7hf-neon-vfpv4-ve-linux-gnueabi
make && c_pt 
#&& make clean
