#!/bin/bash
# We need to create a lock file for the serial port device because the serial
# starter script in venus will periodically test for devices on available
# serial ports. This would make it impossible to communicate to the Pylon's
# without errors
# Use this script to obtain a lock and start a shell
#
. ./functions.sh

SERDEV=ttyUSB1
if [ "$1." != "." ]; then
	SERDEV=$1
	shift
fi

PROG="bash --rcfile /home/root/.bash_profile"

if [ "$1." != "." ]; then
	PROG="$*"
fi

echo "Lock: $SERDEV, PROG: $PROG"

tryLock() {
  while true; do
    lock_tty $SERDEV
    [ $? -eq 0 ] && return 0
    echo -n "."
    sleep 0.5
  done
}

echo -n "Trying to lock $SERDEV "
tryLock
echo "OK, is locked"



echo "starting $PROG"
$PROG
unlock_tty $SERDEV
echo "$SERVEV unlocked"
